import type { Metadata } from "next";

import "@fontsource/roboto";

import { AppThemeProvider } from "@/app/contexts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "Roboto", margin: "0px", padding: "0px" }}>
        <AppThemeProvider>{children}</AppThemeProvider>
      </body>
    </html>
  );
}
